name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: alienbygg/stash-filter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check Docker Hub secrets
      run: |
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "::error::Docker Hub secrets not configured properly"
          echo "::error::Please check DOCKERHUB_USERNAME and DOCKERHUB_TOKEN in repository secrets"
          echo "SKIP_DOCKER_PUSH=true" >> $GITHUB_ENV
        else
          echo "::notice::Docker Hub secrets found"
          echo "SKIP_DOCKER_PUSH=false" >> $GITHUB_ENV
        fi

    - name: Login to Docker Hub
      if: env.SKIP_DOCKER_PUSH == 'false' && github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ env.SKIP_DOCKER_PUSH == 'false' && github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Docker push summary
      run: |
        if [ "${{ env.SKIP_DOCKER_PUSH }}" == "true" ]; then
          echo "::notice::Docker image built but not pushed (missing Docker Hub secrets)"
        else
          echo "::notice::Docker image built and pushed successfully"
        fi

    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}
